doctrine:
    orm:
        mappings:
            App\Product:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Product/Domain'
                prefix: 'App\Product\Domain'
                alias: AppProduct
